GET   http://localhost:3000/

###
GET   http://localhost:3000/users


###
GET   http://localhost:3000/users/3


###
DELETE  http://localhost:3000/users/2

###
POST  http://localhost:3000/users
Content-Type: application/json

{
  "id" : 3,                         
  "nom_livre" : "tintin",       
  "date_de_sortier" : "1970-02-09T00:00:00.000Z", 
  "Favorie" : false         
}

###
PATCH   http://localhost:3000/users
Content-Type: application/json

{ 

 "id":3,               
 "nom_livre" : "dd",       
  "date_de_sortier" : "1990-06-09T00:00:00.000Z", 
  "Favorie" : true            

}


